services:
  jupyter:
    build: 
      context: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./config:/home/jovyan/.jupyter
    networks:
      - mybridge

  mongo:
    image: mongo:4.4-bionic
    container_name: mongo_service
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
      - ./db-seed:/db-seed
      - ./datasets:/datasets
    networks:
      - mybridge

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_service
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:mongo@mongo:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    networks:
      - mybridge
    command: ["/wait-for-it.sh", "mongo:27017", "--", "npm", "start"]

  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    volumes:
      - ./datasets:/datasets
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra-net
      - mybridge

  cassandra-web:
    image: ipushc/cassandra-web
    container_name: cassandra-web-container
    ports:
      - "3000:80"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    environment:
      - HOST_PORT=:80
      - READ_ONLY=false
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=cassandra  
      - CASSANDRA_PASSWORD=cassandra  
    command: ["/wait-for-it.sh", "cassandra:9042", "--", "./service", "-c", "config.yaml"]
    depends_on:
      - cassandra
    networks:
      - cassandra-net
      - mybridge

volumes:
  dbdata:
  db-seed:
  cassandra_data:

networks:
  cassandra-net:
    driver: bridge
  mybridge:
    external: true
    